Personality.create!([
  {name: "Высокая интровертированность", description: "Спокойный, застенчивый, погруженный в свои переживания человек, который отделен от всех, кроме близких людей. Он планирует свои действия заблоговременно, любит во всем порядок и держит свои чувства под строгим контролем. Склонен общаться с близкими, домашний, верный в своих привязанностях, смирный и послушный, воздерживается от шумных компаний и неустойчивых партнеров. Терпимый, смиренный и лояльный к чужим взглядам. Внешне - медлительный, нерешительный, безгласный, но это может быть обманом, поскольку это еще не говорит об его внутреннем мире", personality_trait_id: 1, begin_at: 0.0, end_at: 6.0},
  {name: "Средняя интровертированность", description: "Спокойный, застенчивый, погруженный в свои переживания человек, который отделен от всех, кроме близких людей. Он планирует свои действия заблоговременно, любит во всем порядок и держит свои чувства под строгим контролем. Склонен общаться с близкими, домашний, верный в своих привязанностях, смирный и послушный, воздерживается от шумных компаний и неустойчивых партнеров. Терпимый, смиренный и лояльный к чужим взглядам. Внешне - медлительный, нерешительный, безгласный, но это может быть обманом, поскольку это еще не говорит об его внутреннем мире", personality_trait_id: 1, begin_at: 7.0, end_at: 11.0},
  {name: "Средняя экстравертированность", description: "Общительный, имеет много друзей, не любит долго читать и заниматься систематической учебой, стремление к различного рода возбуждениям (как положительным, так и отрицательным), склонен к риску и приключениям, действует под влиянием момента, импульсивен, беззаботен и добродушно весел, оптимистичен, в жизни предпочитает действие и движение, бывает вспыльчив, эмоции и чувства не всегда контролируются. Из положительных черт: энергичность, инициативность, энтузиазм, стремление к новым сторонам жизни, при реализации своих замыслов бойкий и пробивной, деятельный, с кипучей энергией. Хороший организатор, целеустремленный и предприимчивый. С окружающими жизнерадостный, неунывающий", personality_trait_id: 1, begin_at: 17.0, end_at: 21.0},
  {name: "Высокая экстравертированность", description: "Общительный, имеет много друзей, не любит долго читать и заниматься систематической учебой, стремление к различного рода возбуждениям (как положительным, так и отрицательным), склонен к риску и приключениям, действует под влиянием момента, импульсивен, беззаботен и добродушно весел, оптимистичен, в жизни предпочитает действие и движение, бывает вспыльчив, эмоции и чувства не всегда контролируются. Из положительных черт: энергичность, инициативность, энтузиазм, стремление к новым сторонам жизни, при реализации своих замыслов бойкий и пробивной, деятельный, с кипучей энергией. Хороший организатор, целеустремленный и предприимчивый. С окружающими жизнерадостный, неунывающий", personality_trait_id: 1, begin_at: 22.0, end_at: 26.0},
  {name: "Средняя экстравертированность-интровертированность", description: "Нет предласположенности к интровертированности или экстравертированности", personality_trait_id: 1, begin_at: 12.0, end_at: 16.0},
  {name: " Высокая пластичность", description: "Пластичность (лабильность) - одно из свойств нервной системы, характеризующее скорость возникновения и прекращения нервных процессов", personality_trait_id: 2, begin_at: 0.0, end_at: 2.0},
  {name: "Средняя пластичность", description: "Пластичность (лабильность) - одно из свойств нервной системы, характеризующее скорость возникновения и прекращения нервных процессов", personality_trait_id: 2, begin_at: 3.0, end_at: 6.0},
  {name: "Средняя ригидность-пластичность", description: "нет описания\n", personality_trait_id: 2, begin_at: 7.0, end_at: 11.0},
  {name: "Средняя ригидность", description: "Ригидность - затрудненность в изменении намеченной субъектом программы деятельности в условиях, объективно требующих ее перестройки. Выражается: 1) в косности аффективных (эмоциональных) откликов на изменяющиеся объекты эмоций; 2) в тугоподвижности перестройки системы мотивов в обстоятельствах, требующих от субъекта гибкости и изменения характера поведения; 3) в трудностях перестройки восприятия и представлений в изменившейся ситуации. ", personality_trait_id: 2, begin_at: 12.0, end_at: 15.0},
  {name: "Высокая ригидность", description: "Ригидность - затрудненность в изменении намеченной субъектом программы деятельности в условиях, объективно требующих ее перестройки. Выражается: 1) в косности аффективных (эмоциональных) откликов на изменяющиеся объекты эмоций; 2) в тугоподвижности перестройки системы мотивов в обстоятельствах, требующих от субъекта гибкости и изменения характера поведения; 3) в трудностях перестройки восприятия и представлений в изменившейся ситуации", personality_trait_id: 2, begin_at: 16.0, end_at: 23.0},
  {name: " Высокая эмоциональная уравновешенность", description: "Выдержанный, сдержанный, терпеливый, немногословный, степенный, благоразумный, уравновешанный, ровный в общении, воздержанный от гнева и не возмутимый в ситуации стресса. Терпимый к лишениям, умеренный в своих потребностях. Это психологически устойчивая личность, которая хорошо адаптируется к социальной среде. ", personality_trait_id: 3, begin_at: 0.0, end_at: 3.0},
  {name: "Средняя эмоциональная уравновешенность", description: "Выдержанный, сдержанный, терпеливый, немногословный, степенный, благоразумный, уравновешанный, ровный в общении, воздержанный от гнева и не возмутимый в ситуации стресса. Терпимый к лишениям, умеренный в своих потребностях. Это психологически устойчивая личность, которая хорошо адаптируется к социальной среде", personality_trait_id: 3, begin_at: 4.0, end_at: 7.0},
  {name: "Средняя эмоциональная возбудимость и уравновешенность", description: "Нет описания\n", personality_trait_id: 3, begin_at: 8.0, end_at: 13.0},
  {name: "Средняя эмоциональная возбудимость", description: "Личность эмоционально неустойчивая, подвержена всевозможным психологическим отклонениям, которые ведут к неуравновешанности. Чувствительный, уязвимый, мучается от неприятностей в жизни. Эмоционально тонко чувствующий, деликатный, восприимчивый к отрицательным сигналам извне, стыдливый, смущающийся. Принимает все близко к сердцу, неуверенный в себе и боязливый. Могут проявляться закомплексованность, пугливость, неуверенность в себе, напряженность эмоций. ", personality_trait_id: 3, begin_at: 14.0, end_at: 17.0},
  {name: "Высокая эмоциональная возбудимость", description: "Личность эмоционально неустойчивая, подвержена всевозможным психологическим отклонениям, которые ведут к неуравновешанности. Чувствительный, уязвимый, мучается от неприятностей в жизни. Эмоционально тонко чувствующий, деликатный, восприимчивый к отрицательным сигналам извне, стыдливый, смущающийся. Принимает все близко к сердцу, неуверенный в себе и боязливый. Могут проявляться закомплексованность, пугливость, неуверенность в себе, напряженность эмоций. ", personality_trait_id: 3, begin_at: 18.0, end_at: 20.0},
  {name: " Очень медленный темп реакций", description: "ОиРеакция - действие, состояние, процесс, возникающее в ответ на какое-либо воздействие, раздражитель, впечатление. Реакция - акт поведения, возникающее в ответ на определенное воздействие. сание", personality_trait_id: 4, begin_at: 0.0, end_at: 4.0},
  {name: "Медленный темп реакций", description: "Реакция - действие, состояние, процесс, возникающее в ответ на какое-либо воздействие, раздражитель, впечатление. Реакция - акт поведения, возникающее в ответ на определенное воздействие. ", personality_trait_id: 1, begin_at: 5.0, end_at: 8.0},
  {name: "Средний темп реакций", description: "Реакция - действие, состояние, процесс, возникающее в ответ на какое-либо воздействие, раздражитель, впечатление. Реакция - акт поведения, возникающее в ответ на определенное воздействие. ", personality_trait_id: 4, begin_at: 9.0, end_at: 13.0},
  {name: "Быстрый темп реакций", description: "Реакция - действие, состояние, процесс, возникающее в ответ на какое-либо воздействие, раздражитель, впечатление. Реакция - акт поведения, возникающее в ответ на определенное воздействие. ", personality_trait_id: 4, begin_at: 14.0, end_at: 19.0},
  {name: "Очень быстрый темп реакций", description: "Оисание", personality_trait_id: 4, begin_at: 20.0, end_at: 22.0},
  {name: "Низкий уровень активности", description: "Активность - свойство всего живого как источник преобразования или поддержания ими жизненно значимых связей с окружающим миром. Активность характеризуется обусловленностью производимых действий, произвольностью (наличием цели субъекта), значительной устойчивостью деятельности в отношении принятой цели. ", personality_trait_id: 5, begin_at: 0.0, end_at: 8.0},
  {name: "Активность ниже среднего", description: "Активность - свойство всего живого как источник преобразования или поддержания ими жизненно значимых связей с окружающим миром. Активность характеризуется обусловленностью производимых действий, произвольностью (наличием цели субъекта), значительной устойчивостью деятельности в отношении принятой цели. ", personality_trait_id: 5, begin_at: 9.0, end_at: 13.0},
  {name: "Средняя активность", description: "Активность - свойство всего живого как источник преобразования или поддержания ими жизненно значимых связей с окружающим миром. Активность характеризуется обусловленностью производимых действий, произвольностью (наличием цели субъекта), значительной устойчивостью деятельности в отношении принятой цели. ", personality_trait_id: 5, begin_at: 14.0, end_at: 16.0},
  {name: "Активность выше среднего", description: "Активность - свойство всего живого как источник преобразования или поддержания ими жизненно значимых связей с окружающим миром. Активность характеризуется обусловленностью производимых действий, произвольностью (наличием цели субъекта), значительной устойчивостью деятельности в отношении принятой цели. ", personality_trait_id: 5, begin_at: 17.0, end_at: 23.0},
  {name: "Высокая активность", description: "Активность - свойство всего живого как источник преобразования или поддержания ими жизненно значимых связей с окружающим миром. Активность характеризуется обусловленностью производимых действий, произвольностью (наличием цели субъекта), значительной устойчивостью деятельности в отношении принятой цели. ", personality_trait_id: 5, begin_at: 24.0, end_at: 26.0},
  {name: "Низкая искренность", description: "В ходе обследования испытуемый либо не вполне понимал смысла вопросов, либо торопился заполнить опросник", personality_trait_id: 6, begin_at: 0.0, end_at: 7.0},
  {name: "Средняя искренность", description: " В ходе психологического обследования испытуемый старается достоверно представить свою личность.", personality_trait_id: 6, begin_at: 8.0, end_at: 12.0},
  {name: "Высокая искренность", description: "Высокий уровень искренности при ответах.. Искренность - для личности с таким параметром характерно чистосердечие и человечность в общении. Про такого говорят, что он честный по своей натуре, бескорыстный в своих поступках и помощи. Добросердечность этой личности нельзя смешивать со всепрощением, личность с пониманием относится к чужим проблемам и старается в силу своих возможностей помочь окружающим. Добрый, отзывчивый к окружающим, гуманист. В ходе психологического обследования не старается приукрасить свою личность. \n", personality_trait_id: 6, begin_at: 13.0, end_at: 20.0},
  {name: "аудиальная репрезентативная система", description: "Оисание", personality_trait_id: 7, begin_at: 1.0, end_at: 2.0},
  {name: "визуальная репрезентативная система", description: "Оисание", personality_trait_id: 8, begin_at: 1.0, end_at: 2.0},
  {name: "кинестетическая репрезентативная система", description: "Оисание", personality_trait_id: 9, begin_at: 1.0, end_at: 2.0},
  {name: "думающий, анализирующий, компьютерный тип", description: "Оисание", personality_trait_id: 11, begin_at: 1.0, end_at: 2.0}
])
PersonalityTest.create!([
  {name: "Опросник Смирнова", personality_test_type_id: 1},
  {name: "Тест на модальность", personality_test_type_id: 3}
])
PersonalityTestAnswer.create!([
  {value: "Да", personality_test_question_id: 10},
  {value: "Нет", personality_test_question_id: 10},
  {value: "Да", personality_test_question_id: 9},
  {value: "Нет", personality_test_question_id: 9},
  {value: "Да", personality_test_question_id: 11},
  {value: "Нет", personality_test_question_id: 11},
  {value: "Да", personality_test_question_id: 16},
  {value: "Нет", personality_test_question_id: 16},
  {value: "Да", personality_test_question_id: 17},
  {value: "Нет", personality_test_question_id: 17},
  {value: "Да", personality_test_question_id: 18},
  {value: "Нет", personality_test_question_id: 18},
  {value: "Да", personality_test_question_id: 19},
  {value: "Нет", personality_test_question_id: 19},
  {value: "Да", personality_test_question_id: 20},
  {value: "Нет", personality_test_question_id: 20},
  {value: "Да", personality_test_question_id: 21},
  {value: "Нет", personality_test_question_id: 21},
  {value: "Да", personality_test_question_id: 22},
  {value: "Нет", personality_test_question_id: 22},
  {value: "Да", personality_test_question_id: 23},
  {value: "Нет", personality_test_question_id: 23},
  {value: "Да", personality_test_question_id: 27},
  {value: "Нет", personality_test_question_id: 27},
  {value: "Да", personality_test_question_id: 29},
  {value: "Нет", personality_test_question_id: 29},
  {value: "Да", personality_test_question_id: 32},
  {value: "Нет", personality_test_question_id: 32},
  {value: "Да", personality_test_question_id: 33},
  {value: "Нет", personality_test_question_id: 33},
  {value: "Да", personality_test_question_id: 34},
  {value: "Нет", personality_test_question_id: 34},
  {value: "Да", personality_test_question_id: 35},
  {value: "Нет", personality_test_question_id: 35},
  {value: "Да", personality_test_question_id: 36},
  {value: "Нет", personality_test_question_id: 36},
  {value: "Да", personality_test_question_id: 37},
  {value: "Нет", personality_test_question_id: 37},
  {value: "Да", personality_test_question_id: 39},
  {value: "Нет", personality_test_question_id: 39},
  {value: "Да", personality_test_question_id: 40},
  {value: "Нет", personality_test_question_id: 40},
  {value: "Да", personality_test_question_id: 42},
  {value: "Нет", personality_test_question_id: 42},
  {value: "Да", personality_test_question_id: 43},
  {value: "Нет", personality_test_question_id: 43},
  {value: "Да", personality_test_question_id: 44},
  {value: "Нет", personality_test_question_id: 44},
  {value: "Да", personality_test_question_id: 45},
  {value: "Нет", personality_test_question_id: 45},
  {value: "Да", personality_test_question_id: 46},
  {value: "Нет", personality_test_question_id: 46},
  {value: "Да", personality_test_question_id: 47},
  {value: "Нет", personality_test_question_id: 47},
  {value: "Да", personality_test_question_id: 48},
  {value: "Нет", personality_test_question_id: 48},
  {value: "Да", personality_test_question_id: 49},
  {value: "Нет", personality_test_question_id: 49},
  {value: "Да", personality_test_question_id: 50},
  {value: "Нет", personality_test_question_id: 50},
  {value: "Да", personality_test_question_id: 51},
  {value: "Нет", personality_test_question_id: 51},
  {value: "Да", personality_test_question_id: 52},
  {value: "Нет", personality_test_question_id: 52},
  {value: "Да", personality_test_question_id: 53},
  {value: "Нет", personality_test_question_id: 53},
  {value: "Да", personality_test_question_id: 54},
  {value: "Нет", personality_test_question_id: 54},
  {value: "Да", personality_test_question_id: 55},
  {value: "Нет", personality_test_question_id: 55},
  {value: "Да", personality_test_question_id: 56},
  {value: "Нет", personality_test_question_id: 56},
  {value: "Да", personality_test_question_id: 57},
  {value: "Нет", personality_test_question_id: 57},
  {value: "Да", personality_test_question_id: 58},
  {value: "Нет", personality_test_question_id: 58},
  {value: "Да", personality_test_question_id: 59},
  {value: "Нет", personality_test_question_id: 59},
  {value: "Да", personality_test_question_id: 60},
  {value: "Нет", personality_test_question_id: 60},
  {value: "Да", personality_test_question_id: 61},
  {value: "Нет", personality_test_question_id: 61},
  {value: "Да", personality_test_question_id: 62},
  {value: "Нет", personality_test_question_id: 62},
  {value: "Да", personality_test_question_id: 63},
  {value: "Нет", personality_test_question_id: 63},
  {value: "Да", personality_test_question_id: 64},
  {value: "Нет", personality_test_question_id: 64},
  {value: "Да", personality_test_question_id: 65},
  {value: "Нет", personality_test_question_id: 65},
  {value: "Да", personality_test_question_id: 66},
  {value: "Нет", personality_test_question_id: 66},
  {value: "Да", personality_test_question_id: 67},
  {value: "Нет", personality_test_question_id: 67},
  {value: "Да", personality_test_question_ida: 68},
  {value: "Нет", personality_test_question_id: 68},
  {value: "важные решения – это дело чувств", personality_test_question_id: 13},
  {value: "важные решения зависят от моего настроения", personality_test_question_id: 13},
  {value: "важные решения зависят от моей точки зрения", personality_test_question_id: 13},
  {value: "важные решения – это дело логики и ума", personality_test_question_id: 13},
  {value: "у кого приятный голос", personality_test_question_id: 14},
  {value: "важные решения – это дело логики и умакто хорошо выглядит", personality_test_question_id: 14},
  {value: "кто говорит разумные вещи", personality_test_question_id: 14},
  {value: "кто оставляет у меня хорошие чувства", personality_test_question_id: 14},
  {value: "я посмотрю, как вы выглядите", personality_test_question_id: 69},
  {value: "я проверю, что вы чувствуете", personality_test_question_id: 69},
  {value: "я прислушаюсь к звукам вашего голоса", personality_test_question_id: 69},
  {value: "я обращу внимание на то, что вы говорите", personality_test_question_id: 69},
  {value: "модулировать полноту звуков в стереосистеме", personality_test_question_id: 70},
  {value: "сделать выводы по поводу значимых проблем в интересующем меня вопросе", personality_test_question_id: 70},
  {value: "выбирать суперкомфортабельную мебель", personality_test_question_id: 70},
  {value: "найти богатые комбинации красок", personality_test_question_id: 70},
  {value: "мне очень легко понять смысл новых фактов и данных", personality_test_question_id: 71},
  {value: "мои уши всегда настроены на звуки окружающей действительности", personality_test_question_id: 71},
  {value: "я хорошо чувствую одежду, облегающую мое тело", personality_test_question_id: 71},
  {value: "я легко замечаю все краски мира", personality_test_question_id: 71},
  {value: "им следует узнать о моих чувствах", personality_test_question_id: 72},
  {value: "им следует посмотреть, как я выгляжу", personality_test_question_id: 72},
  {value: "им следует послушать, как я говорю", personality_test_question_id: 72},
  {value: "им следует прислушаться к интонациям моего голоса", personality_test_question_id: 72},
  {value: "услышать факты, о которых вы знаете", personality_test_question_id: 73},
  {value: "увидеть картины, которые вы нарисовали", personality_test_question_id: 73},
  {value: "узнать о ваших чувствах", personality_test_question_id: 73},
  {value: "послушать звучание вашего голоса, звуки происходящих событий", personality_test_question_id: 73},
  {value: "когда я вижу что-то, я верю этому", personality_test_question_id: 74},
  {value: "когда я слышу факты, я верю им", personality_test_question_id: 74},
  {value: "я верю, когда чувствую что-то", personality_test_question_id: 74},
  {value: "я верю только тому, в чем есть для меня смысл", personality_test_question_id: 74},
  {value: "обычно я хорошо чувствую настроения людей", personality_test_question_id: 75},
  {value: "я могу нарисовать лица, различные подробности того, что я видел", personality_test_question_id: 75},
  {value: "я знаю, что именно думают близкие люди по поводу тех или иных вопросов", personality_test_question_id: 75},
  {value: "я хорошо различаю интонацию голосов моих друзей", personality_test_question_id: 75},
  {value: "я учусь понимать какие-то вещи", personality_test_question_id: 76},
  {value: "я учусь делать какие-то вещи", personality_test_question_id: 76},
  {value: "я учусь слушать новое", personality_test_question_id: 76},
  {value: "я учусь видеть новые возможности", personality_test_question_id: 76},
  {value: "приду к выводу, что важные решения принимаются с помощью чувств", personality_test_question_id: 77},
  {value: "приму решение в зависимости от моего настроения", personality_test_question_id: 77},
  {value: "приму те решения, которые вижу наиболее отчетливо", personality_test_question_id: 77},
  {value: "приму их с помощью логики и разума", personality_test_question_id: 77},
  {value: "мне легко вспомнить, как звучит голос моего друга", personality_test_question_id: 78},
  {value: "мне легко вспомнить, как выглядит мой друг", personality_test_question_id: 78},
  {value: "я легко могу вспомнить, как говорил мой друг", personality_test_question_id: 78},
  {value: "мне легко вспомнить, как я чувствую своего друга", personality_test_question_id: 78}
])
# PersonalityTestAnswerPicture.create!([
#   {image_uid: "2014/11/13/92b1x8db7v_osenniy_fon_autumn_background.jpg", personality_test_answer_id: 17},
#   {image_uid: nil, personality_test_answer_id: 4},
#   {image_uid: nil, personality_test_answer_id: 1},
#   {image_uid: nil, personality_test_answer_id: 5},
#   {image_uid: "2014/11/13/4pew9fh097_osenniy_fon_autumn_background.jpg", personality_test_answer_id: 19},
#   {image_uid: "2014/11/13/2z0z0atufq_kamihina2.jpg", personality_test_answer_id: 24},
#   {image_uid: "2014/11/13/8rmkjhfo3l_thumb1.jpg", personality_test_answer_id: 29},
#   {image_uid: "2014/11/13/62zfy2j02p_thumb2.jpg", personality_test_answer_id: 30},
#   {image_uid: "2014/11/14/4xgp3iyven_PS_2_mocco.jpg", personality_test_answer_id: 32}
# ])
PersonalityTestAnswerWeight.create!([
  {value: 0.1, personality_test_answer_id: 8, personality_trait_id: 1},
  {value: 0.9, personality_test_answer_id: 8, personality_trait_id: 2},
  {value: 0.9, personality_test_answer_id: 9, personality_trait_id: 1},
  {value: 0.1, personality_test_answer_id: 9, personality_trait_id: 2},
  {value: 0.1, personality_test_answer_id: 10, personality_trait_id: 1},
  {value: 0.1, personality_test_answer_id: 11, personality_trait_id: 1},
  {value: 1.0, personality_test_answer_id: 15, personality_trait_id: 1},
  {value: 1.0, personality_test_answer_id: 16, personality_trait_id: 3},
  {value: 1.0, personality_test_answer_id: 26, personality_trait_id: 1},
  {value: 2.0, personality_test_answer_id: 22, personality_trait_id: 2},
  {value: 1.0, personality_test_answer_id: 23, personality_trait_id: 1},
  {value: 1.0, personality_test_answer_id: 24, personality_trait_id: 8},
  {value: 5.0, personality_test_answer_id: 24, personality_trait_id: 9},
  {value: 1.0, personality_test_answer_id: 25, personality_trait_id: 8},
  {value: 6.0, personality_test_answer_id: 25, personality_trait_id: 9},
  {value: 2.0, personality_test_answer_id: 28, personality_trait_id: 3},
  {value: 10123.0, personality_test_answer_id: 31, personality_trait_id: 4},
  {value: 0.0, personality_test_answer_id: 31, personality_trait_id: 1},
  {value: 2.0, personality_test_answer_id: 35, personality_trait_id: 1},
  {value: 3.0, personality_test_answer_id: 35, personality_trait_id: 4},
  {value: 3.0, personality_test_answer_id: 37, personality_trait_id: 5},
  {value: 2.0, personality_test_answer_id: 39, personality_trait_id: 6},
  {value: 3.0, personality_test_answer_id: 41, personality_trait_id: 1},
  {value: 3.0, personality_test_answer_id: 43, personality_trait_id: 2},
  {value: 2.0, personality_test_answer_id: 45, personality_trait_id: 3},
  {value: 2.0, personality_test_answer_id: 47, personality_trait_id: 4},
  {value: 3.0, personality_test_answer_id: 49, personality_trait_id: 5},
  {value: 2.0, personality_test_answer_id: 51, personality_trait_id: 6},
  {value: 1.0, personality_test_answer_id: 47, personality_trait_id: 5},
  {value: 3.0, personality_test_answer_id: 53, personality_trait_id: 1},
  {value: 2.0, personality_test_answer_id: 55, personality_trait_id: 2},
  {value: 3.0, personality_test_answer_id: 57, personality_trait_id: 3},
  {value: 3.0, personality_test_answer_id: 59, personality_trait_id: 4},
  {value: 1.0, personality_test_answer_id: 61, personality_trait_id: 4},
  {value: 3.0, personality_test_answer_id: 61, personality_trait_id: 5},
  {value: 1.0, personality_test_answer_id: 63, personality_trait_id: 6},
  {value: 3.0, personality_test_answer_id: 65, personality_trait_id: 1},
  {value: 1.0, personality_test_answer_id: 66, personality_trait_id: 2},
  {value: 2.0, personality_test_answer_id: 67, personality_trait_id: 2},
  {value: 21.0, personality_test_answer_id: 69, personality_trait_id: 3},
  {value: 2.0, personality_test_answer_id: 71, personality_trait_id: 4},
  {value: 3.0, personality_test_answer_id: 73, personality_trait_id: 5},
  {value: 1.0, personality_test_answer_id: 74, personality_trait_id: 6},
  {value: 1.0, personality_test_answer_id: 75, personality_trait_id: 6},
  {value: 1.0, personality_test_answer_id: 78, personality_trait_id: 6},
  {value: 3.0, personality_test_answer_id: 80, personality_trait_id: 2},
  {value: 1.0, personality_test_answer_id: 82, personality_trait_id: 3},
  {value: 3.0, personality_test_answer_id: 84, personality_trait_id: 4},
  {value: 1.0, personality_test_answer_id: 86, personality_trait_id: 4},
  {value: 3.0, personality_test_answer_id: 86, personality_trait_id: 5},
  {value: 3.0, personality_test_answer_id: 88, personality_trait_id: 6},
  {value: 3.0, personality_test_answer_id: 90, personality_trait_id: 1},
  {value: 3.0, personality_test_answer_id: 92, personality_trait_id: 2},
  {value: 3.0, personality_test_answer_id: 94, personality_trait_id: 3},
  {value: 2.0, personality_test_answer_id: 96, personality_trait_id: 4},
  {value: 3.0, personality_test_answer_id: 98, personality_trait_id: 5},
  {value: 3.0, personality_test_answer_id: 100, personality_trait_id: 6},
  {value: 3.0, personality_test_answer_id: 102, personality_trait_id: 1},
  {value: 1.0, personality_test_answer_id: 102, personality_trait_id: 4},
  {value: 2.0, personality_test_answer_id: 103, personality_trait_id: 2},
  {value: 2.0, personality_test_answer_id: 104, personality_trait_id: 2},
  {value: 1.0, personality_test_answer_id: 105, personality_trait_id: 5},
  {value: 3.0, personality_test_answer_id: 106, personality_trait_id: 3},
  {value: 2.0, personality_test_answer_id: 108, personality_trait_id: 4},
  {value: 3.0, personality_test_answer_id: 110, personality_trait_id: 5},
  {value: 3.0, personality_test_answer_id: 112, personality_trait_id: 6},
  {value: 2.0, personality_test_answer_id: 114, personality_trait_id: 1},
  {value: 2.0, personality_test_answer_id: 116, personality_trait_id: 2},
  {value: 3.0, personality_test_answer_id: 118, personality_trait_id: 3},
  {value: 2.0, personality_test_answer_id: 120, personality_trait_id: 4},
  {value: 1.0, personality_test_answer_id: 121, personality_trait_id: 2},
  {value: 3.0, personality_test_answer_id: 122, personality_trait_id: 5},
  {value: 3.0, personality_test_answer_id: 124, personality_trait_id: 6},
  {value: 1.0, personality_test_answer_id: 126, personality_trait_id: 9},
  {value: 1.0, personality_test_answer_id: 127, personality_trait_id: 7},
  {value: 1.0, personality_test_answer_id: 128, personality_trait_id: 8},
  {value: 1.0, personality_test_answer_id: 129, personality_trait_id: 11},
  {value: 1.0, personality_test_answer_id: 130, personality_trait_id: 7},
  {value: 1.0, personality_test_answer_id: 131, personality_trait_id: 8},
  {value: 1.0, personality_test_answer_id: 132, personality_trait_id: 11},
  {value: 1.0, personality_test_answer_id: 133, personality_trait_id: 9},
  {value: 1.0, personality_test_answer_id: 134, personality_trait_id: 8},
  {value: 1.0, personality_test_answer_id: 135, personality_trait_id: 9},
  {value: 1.0, personality_test_answer_id: 136, personality_trait_id: 7},
  {value: 1.0, personality_test_answer_id: 137, personality_trait_id: 11},
  {value: 1.0, personality_test_answer_id: 138, personality_trait_id: 7},
  {value: 1.0, personality_test_answer_id: 139, personality_trait_id: 11},
  {value: 1.0, personality_test_answer_id: 140, personality_trait_id: 9},
  {value: 1.0, personality_test_answer_id: 141, personality_trait_id: 8},
  {value: 123.0, personality_test_answer_id: 26, personality_trait_id: 3},
  {value: 1.0, personality_test_answer_id: 142, personality_trait_id: 11},
  {value: 1.0, personality_test_answer_id: 143, personality_trait_id: 7},
  {value: 1.0, personality_test_answer_id: 144, personality_trait_id: 9},
  {value: 1.0, personality_test_answer_id: 145, personality_trait_id: 8},
  {value: 1.0, personality_test_answer_id: 146, personality_trait_id: 9},
  {value: 1.0, personality_test_answer_id: 147, personality_trait_id: 8},
  {value: 1.0, personality_test_answer_id: 148, personality_trait_id: 11},
  {value: 1.0, personality_test_answer_id: 149, personality_trait_id: 7},
  {value: 1.0, personality_test_answer_id: 150, personality_trait_id: 11},
  {value: 1.0, personality_test_answer_id: 151, personality_trait_id: 8},
  {value: 1.0, personality_test_answer_id: 152, personality_trait_id: 9},
  {value: 1.0, personality_test_answer_id: 153, personality_trait_id: 7},
  {value: 1.0, personality_test_answer_id: 154, personality_trait_id: 8},
  {value: 1.0, personality_test_answer_id: 155, personality_trait_id: 7},
  {value: 1.0, personality_test_answer_id: 156, personality_trait_id: 9},
  {value: 1.0, personality_test_answer_id: 157, personality_trait_id: 11},
  {value: 1.0, personality_test_answer_id: 158, personality_trait_id: 9},
  {value: 1.0, personality_test_answer_id: 159, personality_trait_id: 8},
  {value: 1.0, personality_test_answer_id: 160, personality_trait_id: 11},
  {value: 1.0, personality_test_answer_id: 161, personality_trait_id: 7},
  {value: 1.0, personality_test_answer_id: 162, personality_trait_id: 11},
  {value: 1.0, personality_test_answer_id: 163, personality_trait_id: 9},
  {value: 1.0, personality_test_answer_id: 164, personality_trait_id: 7},
  {value: 1.0, personality_test_answer_id: 165, personality_trait_id: 8},
  {value: 1.0, personality_test_answer_id: 166, personality_trait_id: 9},
  {value: 1.0, personality_test_answer_id: 167, personality_trait_id: 7},
  {value: 1.0, personality_test_answer_id: 168, personality_trait_id: 8},
  {value: 1.0, personality_test_answer_id: 169, personality_trait_id: 11},
  {value: 1.0, personality_test_answer_id: 170, personality_trait_id: 7},
  {value: 1.0, personality_test_answer_id: 171, personality_trait_id: 8},
  {value: 1.0, personality_test_answer_id: 172, personality_trait_id: 11},
  {value: 1.0, personality_test_answer_id: 173, personality_trait_id: 9}
])
PersonalityTestQuestion.create!([
  {value: " Вы любите часто бывать в компании? ", personality_test_question_type_id: 3, personality_test_id: 3, ordering: 1},
  {value: "Я скорее всего скажу:", personality_test_question_type_id: 4, personality_test_id: 6, ordering: 1},
  {value: "Вы избегаете иметь вещи, которые ненадежны, непрочны, хотя и красивы? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 2},
  {value: "Тот скорее окажет влияние на меня", personality_test_question_type_id: 4, personality_test_id: 6, ordering: 2},
  {value: "Часто ли у вас бывают подъемы и спады настроения? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 3},
  {value: "Если я хочу узнать, как вы поживаете,", personality_test_question_type_id: 4, personality_test_id: 6, ordering: 3},
  {value: "Во время беседы вы очень быстро говорите? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 4},
  {value: "Для меня легко", personality_test_question_type_id: 4, personality_test_id: 6, ordering: 4},
  {value: "Вам нравится работа, требующая полного напряжения сил и способностей? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 5},
  {value: "Смогу сказать о себе", personality_test_question_type_id: 4, personality_test_id: 6, ordering: 5},
  {value: " Бывает ли, что вы передаете слухи? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 6},
  {value: "Если люди захотят узнать, как я поживаю", personality_test_question_type_id: 4, personality_test_id: 6, ordering: 6},
  {value: "Считаете ли вы себя человеком очень веселым и жизнерадостным? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 7},
  {value: "Я предпочитаю", personality_test_question_type_id: 4, personality_test_id: 6, ordering: 7},
  {value: "Вы очень привыкаете к определенной одежде, ее цвету и покрою, так что неохотно меняете ее на что-нибудь другое?", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 8},
  {value: "Интересно, что", personality_test_question_type_id: 4, personality_test_id: 6, ordering: 8},
  {value: "Часто ли вы чувствуете, что нуждаетесь в людях, которые вас понимают, могут ободрить или утешить? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 9},
  {value: "Про себя я могу сказать следующее", personality_test_question_type_id: 4, personality_test_id: 6, ordering: 9},
  {value: "У вас очень быстрый почерк? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 10},
  {value: "Чаще всего", personality_test_question_type_id: 4, personality_test_id: 6, ordering: 10},
  {value: "Ищете ли вы сами себе работу, занятие, хотя можно было бы и отдохнуть? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 11},
  {value: "Когда я думаю о принятии нового решения, я скорее", personality_test_question_type_id: 4, personality_test_id: 6, ordering: 11},
  {value: "Бывает ли так, что вы не выполняете своих обещаний? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 12},
  {value: "Я отличаюсь тем, что", personality_test_question_type_id: 4, personality_test_id: 6, ordering: 12},
  {value: "У вас много очень хороших друзей? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 13},
  {value: "Трудно ли вам оторваться от дела, которым вы поглощены, и переключиться на другое? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 14},
  {value: "Часто ли вас терзает чувство вины? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 15},
  {value: " Обычно вы ходите очень быстро, независимо от того, спешите или нет? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 16},
  {value: " В школе вы бились над трудными задачами до тех пор, пока не решали их? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 17},
  {value: " Бывает ли, что вы иногда соображаете хуже, чем обычно? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 18},
  {value: " Вам легко найти общий язык с незнакомыми людьми? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 19},
  {value: " Часто ли вы планируете, как будете себя вести при встрече, беседе и т.д.? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 20},
  {value: " Вы вспыльчивы и легко ранимы намеками и шутками над вами? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 21},
  {value: " Во время беседы обычно вы быстро жестикулируете? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 22},
  {value: " Чаще всего вы просыпаетесь утром свежим и хорошо отдохнувшим? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 23},
  {value: " Бывают ли у вас такие мысли, что вы не хотели бы, чтобы о них знали другие?", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 24},
  {value: " Вы любите подшучивать над другими? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 25},
  {value: " Склонны ли вы к тому, чтобы основательно проверить свои мысли, прежде чем их сообщить кому-либо? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 26},
  {value: " Часто ли вам снятся кошмары? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 27},
  {value: " Обычно вы легко запоминаете и усваиваете новый учебный материал? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 28},
  {value: " Вы настолько активны, что вам трудно даже несколько часов быть без дела? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 29},
  {value: " Бывало ли, что, разозлившись, вы выходили из себя? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 30},
  {value: " Вам не трудно внести оживление в довольно скучную компанию? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 31},
  {value: " Вы обычно довольно долго раздумываете, принимая какое-то, даже не очень важное, решение? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 32},
  {value: " Вам говорили, что вы принимаете все слишком близко к сердцу? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 33},
  {value: " Вам нравится играть в игры, требующие быстроты и хорошей реакции? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 34},
  {value: " Если у вас что-то долго не получается, то обычно вы все же пытаетесь сделать это? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 35},
  {value: " Возникало ли у вас, хотя и кратковременно, чувство раздражения к вашим родителям? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 36},
  {value: " Считаете ли вы себя открытым и общительным человеком? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 37},
  {value: " Обычно вам трудно взяться за новое дело? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 38},
  {value: " Беспокоит ли вас чувство, что вы чем-то хуже других? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 39},
  {value: " Обычно вам трудно что-то делать с медлительными и неторопливыми людьми? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 40},
  {value: " В течение дня вы можете долго и продуктивно заниматься чем-либо, не чувствуя усталости? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 41},
  {value: " У вас есть привычки, от которых следовало бы избавиться? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 42},
  {value: " Вас принимают иногда за человека беззаботного? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 43},
  {value: " Считаете ли хорошим другом только того, чья симпатия к вам надежна и проверена? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 44},
  {value: " Вас можно быстро рассердить? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 45},
  {value: " Во время дискуссии обычно вы быстро находите подходящий ответ? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 46},
  {value: " Вы можете заставить себя долго и продуктивно, не отвлекаясь, заниматься чем-либо? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 47},
  {value: " Бывает, что вы говорите о вещах, в которых совсем не разбираетесь? ", personality_test_question_type_id: 1, personality_test_id: 3, ordering: 48}
])
# PersonalityTestQuestionPicture.create!([
#   {image_uid: "2014/11/13/4zt9tsqbvs_osenniy_fon_autumn_background.jpg", personality_test_question_id: nil},
#   {image_uid: "2014/11/13/2y788vq7pf_osenniy_fon_autumn_background.jpg", personality_test_question_id: nil},
#   {image_uid: "2014/11/13/995elxz55q_osenniy_fon_autumn_background.jpg", personality_test_question_id: nil}
# ])
PersonalityTestQuestionType.create!([
  {name: "один вариант"},
  {name: "несколько вариантов"},
  {name: "Независимые приоритеты"},
  {name: "Приоритеты"}
])
PersonalityTestType.create!([
  {name: "стандартный"},
  {name: "результат делится на время"},
  {name: "max"}
])
PersonalityTrait.create!([
  {name: "Экстраверсия-интроверсия"},
  {name: "Ригидность-пластичность"},
  {name: "Эмоциональная возбудимость-уравновешенность"},
  {name: "Темп реакции"},
  {name: "Активность"},
  {name: "Искренность"},
  {name: "Аудиал"},
  {name: "Визуал"},
  {name: "Кинестетик"},
  {name: "Думающий"}
])